menu: # site menu
  Home: /
  Projects: /projects/
  Archives: /archives/
  Search : /search/
  Feed: /rss.xml

home: # home page configuration
  mode: blog # "blog" or "projects"

blog: # blog page configuration
  title: "Blog" # custom title

projects: # projects page configuration
  title: "Projects" # custom title

search: # search
  enabled: true # set to false to turn off search
  title: "Search" # page title

sidebar:
  recent_projects:
    enabled: true # set false to hide the section
    limit: 5 # how many recent projects to show
  social_buttons: # social buttons
    enabled: true # set to false to turn off social buttons
    inject_iconify: true # set to false to turn off Iconify
    size: 1.6em # icon size
  palette_selector: # palette selector
    enabled: true # set to false to turn off palette selector
    default_dark: midnight-sun # default dark palette
    default_light: paper-and-ink # default light palette
    palette_folder: css/palettes # folder for palette css files

rss: # RSS feed options
  path: rss.xml # output file (relative to root)
  limit: 20 # number of posts
  include_drafts: false
  include_future: false
  mark_encrypted_in_title: true # prefix [Encrypted] to titles
  add_encrypted_element: true # add <encrypted>true</encrypted>

short_url: # short URL options
  enabled: true # set to false to turn off all short URLs
  length: 6 # characters in hash

# Enable comments service (either 'giscus' or 'utterances')
# See https://giscus.app/#repository for giscus settings
# See https://utteranc.es/#install for utterances settings
comments:
  enabled: true
  service: giscus # Options: 'giscus', 'utterances'
  giscus:
    repo: "username/repository" # [Required]
    repo_id: "R_..." # [Required]
    category: "General" # [Required]
    category_id: "DIC_..." # [Required]
    mapping: "pathname"
    reactions_enabled: "1"
    emit_metadata: "0"
    input_position: "top"
    theme: "preferred_color_scheme"
    lang: "en"
  utterances:
    repo: "username/repository" # [Required]
    issue_term: "pathname"
    label: "comments"
    theme: "github-light"

swc:
  enabled: true # set to false to turn off SWC
  target: es2020 # target environment
  minify: true # set to false to disable minification
  include: # folders to include
    - js/
  exclude: [] # folders to exclude

read_time: # read time options
  enabled: true # set to false to turn off read time
  write_front_matter: true # write read time to front matter

# Show theme credit. Feeds our ego. Please, we're starving.
attribution: # attribution options
  enabled: true # set to false to turn off attribution
  link: https://github.com/LTDev-LLC/hexo-theme-flux-palette
  text: Flux Palette by LTDev LLC